### ISSUE TITLE
Stash Critical Blunder

### ISSUE THREAD

**Issue by SlowChess** [mhouppin/stash-bot#108] opened 2023-06-15 20:06 UTC
![Analysis Board - 365Chess](https://github.com/mhouppin/stash-bot/assets/132969765/0ff32d45-0612-4f4b-83bd-5d998f53dbc1)

1k5r/pp1qbp1p/4bp2/3p3N/2rP4/4PBP1/P4P1P/R2Q1RK1 b - - 0 19

**Comment by mhouppin** [comment] 2023-06-16 10:11
I'm sorry, but this issue lacks basic information on what the problem actually is, how to reproduce it, which version was used, etc.
In any case, yes, Stash will blunder/misevaluate positions in the middlegame, and the only existing "fix" is improving the search/eval until it doesn't blunder anymore.

Since this does not reference a bug or a blatant problem with the engine's behavior, I'm closing this issue.

**Closed by mhouppin** 2023-06-16 10:11 UTC

**Comment by SlowChess** [comment] 2023-06-16 13:23
Bh3 is blunder , I am using the latest version of Stash.

> In any case, yes, Stash will blunder/misevaluate positions in the middlegame, and the only existing "fix" is improving the search/eval until it doesn't blunder anymore.

If you want , I can design NNUE for stash engine but I need your help too.

**Comment by mhouppin** [comment] 2023-06-16 14:55
NNUE support isn't planned in Stash anytime soon.

**Comment by SlowChess** [comment] 2023-06-16 16:11
NNUE support isn't hard for Stash because Stash structure is the same Ethereal and Stockfish.

I believe that if we enable NNUE for Stash then Stash comes in TOP 10 Chess ranking.

Just see BH3 blunder , It cause decrease at least 200 Elo rating.

**Comment by SlowChess** [comment] 2023-06-16 19:00
@mhouppin if you give me stash license , I'll create NNUE for Stash  as soon as possible.

**Comment by mhouppin** [comment] 2023-06-17 07:55
You might have misunderstood me. When I dais that "NNUE support isn't planned in Stash anytime soon", I meant that NNUE will not be part of the engine ever. This is a decision I took a while ago, because of how I want the engine to develop in the future. Stash will remain HCE.

**Comment by SlowChess** [comment] 2023-06-17 19:25
OK ....

But if you even calculate to depth 99 , you can't find bestmove in this position. Just do it...

**Comment by mhouppin** [comment] 2023-06-18 07:09
Again, Stash will blunder/misevaluate positions in the middlegame, and the only existing "fix" is improving the search/eval until it "magically" plays the correct move in these. There's no specific section of the code that handles this position, so there's no quick fix that I can do to improve this.
Test positions are a really poor tool for measuring engine ratings. Improving an engine's rating is not about solving test positions. Please stop commenting on this issue.

**Comment by SlowChess** [comment] 2023-06-18 14:55
> Again, Stash will blunder/misevaluate positions in the middlegame

Here is blunder/misevaluate positions in the endgame,
![Screenshot 2023-06-07 at 14-45-53 Analysis Board - 365Chess](https://github.com/jhonnold/berserk/assets/132969765/3173802e-8734-4cfe-8f38-b579d53e2fff)

8/4b2k/2b3pp/1p2p3/p3N1PP/P1N1P1K1/1P6/8 w - - 0 56

> so there's no quick fix that I can do to improve this.

There is a way to quick fix , I want to write  the Commercial version of Stash engine if you give me Stash license for do this?

> and the only existing "fix" is improving the search/eval until it "magically" plays the correct move in these.

Although improving the search/eval make magically engine but we see even SF has too many blunder!

- https://github.com/glinscott/nnue-pytorch/issues/250

> Please stop commenting on this issue.

If you are not interested to discuss about it so I'll not comment for you?😢

**Comment by mhouppin** [comment] 2023-06-19 08:35
I can't _give you_ the License, it's already there in the repo. Just read it. You might find it quite difficult to make a commercial engine out of mine considering it's licensed under the GPLv3.
You again posted a position out of nowhere that Stash misevaluates. Again, Stash will blunder/misevaluate positions, **in the endgame and the opening as well**.
Please stop posting on this issue. This is my last warning.

**Comment by ginkgo20** [comment] 2023-08-14 17:18
> Again, Stash will blunder/misevaluate positions, **in the endgame and the opening as well**.

Soon I will implement the neural network on your engine andStash's mistakes will be minimized.
